### ISSUE TITLE
Don't know how, but lost a file.

### ISSUE THREAD

**Issue by mnott** [PDF-Archiver/PDF-Archiver#7] opened 2018-03-08 14:56 UTC
Have 6 files, imported / tagged three, two got moved into the target folder, one just went missing.

**Comment by JulianKahnert** [comment] 2018-03-08 19:12
Hey, thanks for reporting this issue:
could you please explain your workflow in detail?

**Comment by JulianKahnert** [comment] 2018-03-17 22:53
Hey @mnott, I have just released a new version (1.1.3). Can you reproduce this problem on this version?

**Comment by JulianKahnert** [comment] 2018-03-26 20:43
I am closing this since there is no new reaponse.

**Closed by JulianKahnert** 2018-03-26 20:43 UTC
